language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: IKmwJti/tV9u7MNKTixUjghzN8pIDU5TZr8W0OlxFykxikRZtTKhqW/2dulmedRji5KxcknaUBy06fvFgo7cEPl6RSpuHm5LzNGIhB+pc9b4nPF0frXMBwhm3YQIpcfeH8xmO/cxfefoccryLxRSP7e+3RaX5Z3c9pbnrgnqPQeynkxyekdxGKd0Ncziuv7mD6o7MbWA3Kb+TSr9dlcXNQOHpuTU9SCNrgLN20KT46sdMlqAJQepGYdfyf7lHKEf+EhJ2kZbNeztfxjr9lq7gH//7qIIg7WGGcIe7QzMUY6pa1XOZkvBJvSzv7LgWoZ5r2RSurtA/2J/o24GZH5erCn6oQtMLWQn2jA/TkkhkAAhbqLxovp3beLFxYSY0t8rfSzICuDntv/80FpItrVRLWZpbN2BREZ6vw0+RcBXMmMj+XqBBOzzQ6QGt+xWkuDieutAhBDK1qV3ubunp298edYYWP1XAAVVvwjsQ2C5dASc6fyrGCO/v91k13j4hmbH2NGEnV/teVs3uwEPjbhKNPsRYk65ZUw8oYr7HPIWznD4WHkuJQPz3Pg6PfDR2FnlVxq+9wH/a1niunTcXA4PJHCxPuCYB55wbo1Wwelml6k95XkMpHcH0iaECmATlecPtNyQCtgBkxdh+lGvIWBAgaUizgNyBZ4Y9k6zly7sdlw=
  app: pizzeria2
  on:
    repo: JayeRemi/Pizzeria

env:
  global:
    - CC_TEST_REPORTER_ID=1ead3746b2874a5728713b5cf8ba77e1ec9160dfdd891c99eecccd59fbb1d4b0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT