language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: IKmwJti/tV9u7MNKTixUjghzN8pIDU5TZr8W0OlxFykxikRZtTKhqW/2dulmedRji5KxcknaUBy06fvFgo7cEPl6RSpuHm5LzNGIhB+pc9b4nPF0frXMBwhm3YQIpcfeH8xmO/cxfefoccryLxRSP7e+3RaX5Z3c9pbnrgnqPQeynkxyekdxGKd0Ncziuv7mD6o7MbWA3Kb+TSr9dlcXNQOHpuTU9SCNrgLN20KT46sdMlqAJQepGYdfyf7lHKEf+EhJ2kZbNeztfxjr9lq7gH//7qIIg7WGGcIe7QzMUY6pa1XOZkvBJvSzv7LgWoZ5r2RSurtA/2J/o24GZH5erCn6oQtMLWQn2jA/TkkhkAAhbqLxovp3beLFxYSY0t8rfSzICuDntv/80FpItrVRLWZpbN2BREZ6vw0+RcBXMmMj+XqBBOzzQ6QGt+xWkuDieutAhBDK1qV3ubunp298edYYWP1XAAVVvwjsQ2C5dASc6fyrGCO/v91k13j4hmbH2NGEnV/teVs3uwEPjbhKNPsRYk65ZUw8oYr7HPIWznD4WHkuJQPz3Pg6PfDR2FnlVxq+9wH/a1niunTcXA4PJHCxPuCYB55wbo1Wwelml6k95XkMpHcH0iaECmATlecPtNyQCtgBkxdh+lGvIWBAgaUizgNyBZ4Y9k6zly7sdlw=
  app: pizzeria2
  on:
    repo: JayeRemi/Pizzeria

