# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 434a3c093aefafcfaf38e119d12a5ece1cb5ebee29942014424d9f2edb20dbf47a2abd4b2d12bae40d345cd0f7d0f7789e3fd86baea0e3108412fc4b8e234a2f

test:
  secret_key_base: cc55e827c51bb9bb3cf05bded9e84c6326b939188b46b13ffeeb0108112925ac891f8bdc109b99a06f4963a0488d2377962fd98bebbb91019b1fb0a8c30938ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
